### ISSUE TITLE
Allow to set parameters

### ISSUE THREAD

**Issue by heshanlk** [mchljams/gcia#1]
We cannot set parameters so there should be a way to specify the global and local parameters.

**Comment by mchljams** [comment]
Can you give me a little more information about what you are trying to do? It is definitely a work in progress.

**Comment by heshanlk** [comment]
First of all thanks for the great work, this looks amazing, but for example, if you go here and try to enter other details like roles https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress#try-it there is no way to do that within the lib so maybe giving the option to alter the $options would be the way to go.

So for example 

`public function representativeInfoByAddress($address)`

can change into

`public function representativeInfoByAddress($address, $params = [])`

so it can allow additional params and it will also be backward compatible.

But that isn't going to fix the issue when we have multiple params with the same key so for example 

`https://content.googleapis.com/civicinfo/v2/representatives?address=10314&levels=country&roles=legislatorUpperBody&roles=legislatorLowerBody&alt=json
`
there is no way http_build_query to build the query with two roles params `roles=legislatorUpperBody&roles=legislatorLowerBody`

So there should be a workaround for that too.

**Comment by heshanlk** [comment]
@mchljams please review this #2
